comment:
  layout: "header, diff, flags, condensed_files"
  # TODO: remove; temporary to test PR comment
  # https://docs.codecov.com/docs/pull-request-comments#requiring-the-base-andor-head-commit
  require_base: false
