# Inherits global settings from https://app.codecov.io/account/gh/python/yaml/
# TODO: enable status checks to fail CI if coverage drops?
# https://docs.codecov.com/docs/commit-status
comment:
  # https://docs.codecov.com/docs/pull-request-comments
  layout: "header, diff, flags, files"
  # TODO: remove; temporary to test PR comment
  # https://docs.codecov.com/docs/pull-request-comments#requiring-the-base-andor-head-commit
  require_base: false
  require_head: false
